apiVersion: v1
kind: ServiceAccount
metadata:
  name: starboard
  namespace: kube-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: starboard-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["watch","get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: starboard-role-bind
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: starboard 
    apiGroup: ""
roleRef:
  kind: Role
  name: starboard-role
  apiGroup: "" 
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: starboard-ds
  namespace: kube-system
  labels:
spec:
  selector:
    matchLabels:
      name: starboard-ds 
  template:
    metadata:
      labels:
        name: starboard-ds 
    spec:
      hostNetwork: true
      serviceAccountName: starboard
      containers:
      - name: starboard-ds
        image: plndr/starboard:0.1.1
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN